# Generated by Django 5.1.6 on 2025-03-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20250302_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activity_group',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='member',
            name='born_again',
            field=models.CharField(default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='bus_stop',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='invited_by',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='office_address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='member',
            name='prayer_request',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='want_membership',
            field=models.CharField(default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
