# Generated by Django 5.1.6 on 2025-03-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_activity_group_member_age_member_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='day',
        ),
        migrations.AlterField(
            model_name='member',
            name='activity_group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='born_again',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='bus_stop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='invited_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='prayer_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='want_membership',
            field=models.BooleanField(),
        ),
    ]
