# Generated by Django 5.1.6 on 2025-03-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_contact_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='activity_group',
        ),
    ]
