# use name to identify the action 
name: Build and Push Docker Image

on: 
  # Trigger the action when pushing to certain branches
  push:
    branches:
      - "main"

# set an env
env:
  DOCKER_IMAGE_NAME: cgcl_church_application

# job are async
# steps are sync
jobs:
  # set a name for job
  build:
    name: Build Docker Images

    # Runner in use
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{vars.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # - name: Build Docker image
      #   uses: docker/setup-buildx-action@v3

      - name: Build and Push image 
        uses: docker/build-push-action@v6
        with:
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          # provenance: true
          # sbom: trues